# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.producer.example.com:
    container_name: peer0.producer.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.producer.example.com
      - CORE_PEER_ADDRESS=peer0.producer.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.producer.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.producer.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.producer.example.com:7051
      - CORE_PEER_LOCALMSPID=ProducerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/producer.example.com/peers/peer0.producer.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/producer.example.com/peers/peer0.producer.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.producer.example.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer0.alazharuniversity.example.com:
    container_name: peer0.alazharuniversity.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.alazharuniversity.example.com
      - CORE_PEER_ADDRESS=peer0.alazharuniversity.example.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.alazharuniversity.example.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.alazharuniversity.example.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.producer.example.com:9051
      - CORE_PEER_LOCALMSPID=AlazharuniversityMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/alazharuniversity.example.com/peers/peer0.alazharuniversity.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/alazharuniversity.example.com/peers/peer0.alazharuniversity.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.alazharuniversity.example.com:/var/hyperledger/production
    ports:
      - 9051:9051
      
  peer0.islamicuniveristy.example.com:
    container_name: peer0.islamicuniveristy.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.islamicuniveristy.example.com
      - CORE_PEER_ADDRESS=peer0.islamicuniveristy.example.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.islamicuniveristy.example.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.islamicuniveristy.example.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.islamicuniveristy.example.com:10051
      - CORE_PEER_LOCALMSPID=IslamicuniveristyMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/islamicuniveristy.example.com/peers/peer0.islamicuniveristy.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/islamicuniveristy.example.com/peers/peer0.islamicuniveristy.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.islamicuniveristy.example.com:/var/hyperledger/production
    ports:
      - 10051:10051
      
      
  peer0.omelkorrauniversity.example.com:
    container_name: peer0.omelkorrauniversity.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.omelkorrauniversity.example.com
      - CORE_PEER_ADDRESS=peer0.omelkorrauniversity.example.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.omelkorrauniversity.example.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.omelkorrauniversity.example.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.omelkorrauniversity.example.com:11051
      - CORE_PEER_LOCALMSPID=OmelkorrauniversityMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/omelkorrauniversity.example.com/peers/peer0.omelkorrauniversity.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/omelkorrauniversity.example.com/peers/peer0.omelkorrauniversity.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.omelkorrauniversity.example.com:/var/hyperledger/production
    ports:
      - 11051:11051
      
  caProducer:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-producer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.producer.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/8608ca5cf5f20f1b84cbe1fd7e2412b71fdc6c61373a61722c859328cdb0d273_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.producer.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/8608ca5cf5f20f1b84cbe1fd7e2412b71fdc6c61373a61722c859328cdb0d273_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/producer.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
      
  caAlazharuniversity:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-alazharuniversity
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.alazharuniversity.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/866daae31d93ae24f04e1fd031d8eabe695e11517947b870e969367271698518_sk
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.alazharuniversity.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/866daae31d93ae24f04e1fd031d8eabe695e11517947b870e969367271698518_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/alazharuniversity.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
      
  caIslamicuniveristy:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-islamicuniveristy
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.islamicuniveristy.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b6bee49e84595b7954fac3ea90a13c3271dbd9992de5d757bdd070558023126a_sk
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.islamicuniveristy.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/b6bee49e84595b7954fac3ea90a13c3271dbd9992de5d757bdd070558023126a_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/islamicuniveristy.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
      
      
  caOmelkorrauniversity:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-omelkorrauniversity
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.omelkorrauniversity.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/da5c525ade6e0c857f294e96df4a5c4d37bcca443e59b42cae4cffe2670f3a65_sk
      - FABRIC_CA_SERVER_PORT=10054
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.omelkorrauniversity.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/da5c525ade6e0c857f294e96df4a5c4d37bcca443e59b42cae4cffe2670f3a65_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/omelkorrauniversity.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
