OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Producer
    Domain: producer.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Alazharuniversity
    Domain: alazharuniversity.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Islamicuniveristy
    Domain: islamicuniveristy.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Omelkorrauniversity
    Domain: omelkorrauniversity.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
