# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.producer.example.com:
  peer0.alazhar-university.example.com:
  peer0.islamicuniveristy.example.com:
  peer0.omelkorra-university.example.com:
  caProducer:
  caAlazharuniversity:
  caIslamicuniveristy:
  caOmElkorauniversity:

networks:
  byfn:

services:

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - byfn

  peer0.producer.example.com:
    container_name: peer0.producer.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.producer.example.com
    networks:
      - byfn

  peer0.alazhar-university.example.com:
    container_name: peer0.alazhar-university.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.alazhar-university.example.com
    networks:
      - byfn

  peer0.islamicuniveristy.example.com:
    container_name: peer0.islamicuniveristy.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.islamicuniveristy.example.com
    networks:
      - byfn

  peer0.omelkorra-university.example.com:
    container_name: peer0.omelkorra-university.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.omelkorra-university.example.com
    networks:
      - byfn

  caProducer:
    container_name: caProducer
    extends:
      file:  base/docker-compose-base.yaml
      service: caProducer
    networks:
      - byfn

  caAlazharuniversity:
    container_name: caAlazharuniversity
    extends:
      file:  base/docker-compose-base.yaml
      service: caAlazharuniversity
    networks:
      - byfn

  caIslamicuniveristy:
    container_name: caIslamicuniveristy
    extends:
      file:  base/docker-compose-base.yaml
      service: caIslamicuniveristy
    networks:
      - byfn

  caOmElkorauniversity:
    container_name: caOmElkorauniversity
    extends:
      file:  base/docker-compose-base.yaml
      service: caOmElkorauniversity
    networks:
      - byfn


  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.islamicuniveristy.example.com:10051
      - CORE_PEER_LOCALMSPID=IslamicuniveristyMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/islamicuniveristy.example.com/peers/peer0.islamicuniveristy.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/islamicuniveristy.example.com/peers/peer0.islamicuniveristy.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/islamicuniveristy.example.com/peers/peer0.islamicuniveristy.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/islamicuniveristy.example.com/users/Admin@islamicuniveristy.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.producer.example.com
      - peer0.alazhar-university.example.com
      - peer0.islamicuniveristy.example.com
      - peer0.omelkorra-university.example.com
      - caProducer
      - caAlazharuniversity
      - caIslamicuniveristy
      - caOmElkorauniversity
    networks:
      - byfn
